version: '3'
services:
 caddy:
  image: hunnguye/caddy_v1.0.4_csr:latest #hunnguye/caddy-alpine-x86_64:v1.0.4
  volumes:
   - "./caddy/srv:/srv"
  depends_on:
   - mysql
  ports:
   - "80:80"
   - "443:443"
  links:
   - tomcat:tomcat
   - php:php
  environment:
   - CADDYPATH=/srv/caddy_home/
  networks:
   - scc

 php:
  image: php:7.4.2-fpm-buster
  volumes:
   - "./www:/srv"
  networks:
   - scc

 tomcat:
  image: tomcat:9.0.29-jdk8-openjdk
  ports:
   - "8080:8080"
  depends_on:
    - mysql
  volumes:
#   - ./tomcat:/usr/local/tomcat
   - ./webapps:/usr/local/tomcat/webapps
  links:
   - mysql:mysql
  networks:
   - scc

 mysql:
  image: mysql:8
  networks:
   - scc
  env_file:
   - ./config/mysql_credentials
  volumes:
   - "./mysql/db:/var/lib/mysql"
   - "./mysql/init:/docker-entrypoint-initdb.d"
networks:
 scc: 
