version: '3'
services:
 mysql:
  image: mysql:5.7
  env_file:
   - ./config/mysql_credentials
  volumes:
#   - "./mysql/db:/var/lib/mysql"
   - "./mysql/init:/docker-entrypoint-initdb.d"
  ports:
   - 3306:3306
